apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: 'evergreen-app-metrics'
        static_configs:
          - targets: ['evergreen-app-service:8080']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']