apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  user: "evergreen"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  labels:
    component: grafana
type: Opaque
data:
  admin-password: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana:latest-ubuntu
          name: grafana
          ports:
          - containerPort: 3000
          env:
          - name: GF_SECURITY_ADMIN_USER
            valueFrom: 
              configMapKeyRef:
                name: grafana-config
                key: user
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-secret
                key: admin-password
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer